---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: "cities"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_DB: 
  MYSQL_PASSWORD: mysqldb

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-db
  labels:
    name: mysql
    tier: db
spec:
  containers:
  - name: mysqldb
    image: mysql:k8
    imagePullPolicy: Always
    envFrom:
      - configMapRef:
          name: mysql-config
      - secretMapRef:
          name: mysql-secret
    ports:
      - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec: 
  selector:
    name: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
...