---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: appserver
spec:
  replicas: 3
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      labels:
        type: appserver
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 80
            hostPort: 8080
...