---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    server: proxy
spec:
  replicas: 50
  selector:
    matchLabels:
      server: proxy
  template:
    metadata:
      labels:
        server: proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          requests:
            cpu: "0.3" # 1 CPU = 1000 m
            memory: "600Mi"
          limits:
            cpu: "0.4"
            memory: "800Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    server: proxy
spec:
  type: LoadBalancer
  selector:
    server: proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
...