---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  labels:
    server: proxy
spec:
  replicas: 6
  selector:
    matchLabels:
      server: proxy
  template:
    metadata:
      labels:
        server: proxy
    spec:
      containers:
      - name: alpine
        image: alpine:1.14.2
        ports:
          - containerPort: 80
            hostPort: 8080
        resources:
          requests:
            cpu: "150m" # 1 CPU = 1000 m
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "300Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    server: proxy
spec:
  type: LoadBalancer
  selector:
    server: proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
...