---
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-weight
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: tier
            operator: NotIn
            values:
            - web
      - weight: 50
        preference:
          matchExpressions:
          - key: tier
            operator: In
            values:
            - web
  containers:
  - name: nginx
    image: nginx
    

...