---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
    tier: db
spec:
  containers:
  - name: rabbitmq
    image: rabbitmq
    imagePullPolicy: Always
    ports:
      - containerPort: 5672
      - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    name: rabbitmq
    tier: db
  ports:
    - port: 5672 # this protocol to a service called message queue for sending logs
      name: amqp
    - port: 15672 #this protocol to browser for accessing
      name: http 
  type: ClusterIP

...