---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongodb
    tier: db
spec:
  selector:
    name: mongo-db
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongo-db
    tier: db
spec:
  containers:
  - name: mongodb
    image: mongodb:v1
    imagePullPolicy: Always
    ports:
      - containerPort: 27017

...