---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    author: kumar
    type: ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      type: ci-cd
  template:
    metadata:
      name: jenkins-pod
      labels:
        type: ci-cd
    spec:
      containers:
        - name: jenkins-pod
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              hostPort: 8080
...
