---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  labels:
    author: kumar
    labels: appserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: mytomcat
          image: tomee
          ports:
            - containerPort: 8080
              hostPort: 9090
...
