---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    type: mysqldb
spec:
  containers:
    - name: mysql
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: a
...
