---
apiVersion: v1
kind: Pod
metadata:
  name: posql-password
  labels:
    type: password
spec:
  containers:
    - name: postgresdb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: password
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: username
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: db
...
