---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-repcon
  labels:
    author: kumar
    labels: appserver
spec:
  replicas: 2
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: mytomcat
          image: tomee
          ports:
            - containerPort: 8080
              hostPort: 9090
...
