---
apiVersion: v1
kind: ReplicationController
metadata:
  name: posql-repcon
  labels:
    author: kumar
    type: postgres
spec:
  replicas: 2
  template:
    metadata:
      name: posql-pod
      labels:
        type: postgres
    spec:
      containers:
        - name: mypostgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: intelliqit
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_DB
              value: mydb
...
