---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    author: kumar
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30450
  selector:
    type: webserver
...
