---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    author: kumar
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30451
  selector:
    type: appserver
...
