---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    author: kumar
    type: servport
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30010
  selector:
    type: servport
...
