---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    AUthor: kumar
    type: webserver
spec:
  replicas: 2
  template:
    metadata:
      name: httpd-pod
      labels:
        author: kumar
        type: webserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
...
