---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    author: kumar
    type: DB
spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb
...
