---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis
    tier: db
spec:
  selector:
    name: redis-db
    tier: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Pod
metadata:
  name: redisdb-pod
  labels:
    name: redis-db
    tier: db
spec:
  containers:
  - name: redisdb
    image: redis
    imagePullPolicy: Always
    ports:
      - containerPort: 6379
      
...