---
apiVersion: v1
kind: LimitRange
metadata: 
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
    defaultRequest: # this section defines default limit requests
      cpu: 500m
    max: # max & min define limit ranges
      cpu: "1"
    min: 
      cpu: "100m"
    type: Container
  
---
apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
  - name: stress
    image: techworldwithsiva/stress
    imagePullPolicy: Always
    command: ["sleep","200"]
...