---
apiVersion: v1
kind: Pod
metadata:
  name: postgres_db
  labels:
    type: postgres
spec:
  containers:
  - name: postgres_db
    image: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: POSTGRES_DB
      value: postgres
    - name: POSTGRES_USER
      value: myuser

...