---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: course
    - name: duration
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: duration

#alternate method
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  labels:
    author: kumar
    type: valureference
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - configMapRef:
          name: course-config
...