---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  labels:
    author: kumar
    type: valureference
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - configMapRef:
          name: course-config
...