---
apiVersion: v1
kind: Pod
metadata:
  name: postgres_db
  labels:
    author: kumar
    type: postgres
spec:
  containers:
  - name: postgres-prod
    image: postgres
    envFrom:
      - secretRef:
          name: mysqldb_det