---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-prod
  labels:
    author: kumar
    type: mysqldetails
spec:
  containers:
  - name: mysqldb
    image: mysql:5
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysqldb_det
            key: password
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysqldb_det
            key: username
      - name: MYSQL_DB
        valueFrom:
          secretKeyRef:
            name: mysqldb_det
            key: dbname

---
apiVersion: v1
kind: Pod
metadata:
  name: postgres_db
  labels:
    author: kumar
    type: postgres
spec:
  containers:
  - name: postgres-prod
    image: postgres
    env:
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysqldb_det
            key: password
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: mysqldb_det
            key: username
      - name: POSTGRES_DB
        valueFrom:
          secretKeyRef:
            name: mysqldb_det
            key: mydb
...